### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by Muvkina** [vincens2005/lite-xl-discord#1]
Hello! Firstly really cool plugin you have here however testing on windows I don't seem to have any status. Is there any other steps outside of the README? I tried running the update rpc and start rpc commands in lite-xl.

**Comment by vincens2005** [comment]
try running lite-xl from the command line and check its output. There might be some kind of error with the python code

**Comment by Muvkina** [comment]
Sorry for leaving this open for a bit have been busy. Currently not using lite-xl so feel free to close this for now if you'd like.

**Comment by vincens2005** [comment]
That's okay, I'll look into the issue anyways. I'm working on rewriting the python component in C, which should make things a lot less jank

**Comment by MillaBasset** [comment]
Ran lite-xl from the command line and I didn't get any output, but the RPC still doesn't work. Windows 10 user here, verified I have every dependency installed.

**Comment by vincens2005** [comment]
okay, i'm not particularly surprised. if you'd like to deal with a build system and make some minor code changes, checkout the clib branch, which is much less janky but only currently supports linux. i'll probably port it to windows at some point but if you wanna do that i'd be glad to not have to

**Comment by MillaBasset** [comment]
I'll see what I can do, thanks

**Comment by vincens2005** [comment]
https://github.com/TorchedSammy/litepresence supports windows
