### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by sonich2401** [vincens2005/lite-xl-discord#6]
Presence updater opens thousands of instances of itself all of the time.
You can see my task manager in this video

https://user-images.githubusercontent.com/34013705/145739306-afed8106-a809-4035-89d8-239ea2595391.mp4

#### Lite info
Lite-XL  ver 2.0.3 (latest release of Dec 12, 2021)
Discord Plugin: Latset of Dec 12, 2021

#### Hardware Information:

System:    Host: linux Kernel: 5.11.0-41-generic x86_64 bits: 64 compiler: N/A Desktop: Xfce 4.14.2 
           Distro: Ubuntu 20.04.3 LTS (Focal Fossa) 
Machine:   Type: Laptop System: HP product: HP Laptop 17-ca0xxx v: N/A serial: <superuser/root required> 
           Mobo: HP model: 84D0 v: 90.40 serial: <superuser/root required> UEFI: AMI v: F.41 date: 05/31/2019 
Battery:   ID-1: BAT0 charge: 12.0 Wh condition: 17.3/17.3 Wh (100%) model: Hewlett-Packard Primary status: Charging 
CPU:       Topology: Dual Core model: AMD A9-9425 RADEON R5 5 COMPUTE CORES 2C+3G bits: 64 type: MCP arch: Excavator 
           L2 cache: 1024 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 12377 
           Speed: 1566 MHz min/max: 1400/3100 MHz Core speeds (MHz): 1: 1525 2: 1558

**Comment by vincens2005** [comment]
Yeah this plugin is very janky. If you want, try cloning the `clib` branch and running that version. It uses the lua C API to communicate with discord, however it might cause lite-xl to crash on start. I was working on converting _that_ to the new native plugin API, but that still has issues, so for the time being if neither one works (and you don't want to fix it yourself), you're out of luck
